USE DBREAD

-- Comando global
DECLARE @COMANDO VARCHAR(8000)

-- Quantidade de colunas da tabela
DECLARE @QTDCOLUNAS INT = 2

-- Quantidade total de registros
DECLARE @QTDTOTALREGISTROS INT = 6

-- Nome da tabela temporária base a ser criada (Fazendo o replace do '_')
DECLARE @NOMETABELA VARCHAR(30) = '@TBCOLUNA_'

-- Tabela exemplo com os dados a serem dividos
SET @COMANDO = 'DECLARE @TODOSITENS TABLE(
						ID INT IDENTITY,
						NOME VARCHAR(50)
						)' + CHAR(13) +

'INSERT INTO @TODOSITENS (NOME) VALUES (''1-A'')' + CHAR(13) +
'INSERT INTO @TODOSITENS (NOME) VALUES (''1-B'')' + CHAR(13) +
'INSERT INTO @TODOSITENS (NOME) VALUES (''1-C'')' + CHAR(13) +
'INSERT INTO @TODOSITENS (NOME) VALUES (''2-D'')' + CHAR(13) +
'INSERT INTO @TODOSITENS (NOME) VALUES (''2-E'')' + CHAR(13) +
'INSERT INTO @TODOSITENS (NOME) VALUES (''2-F'')'  + CHAR(13)

-- Contador global
DECLARE @CONTADOR INT = 0

-- Comando para declaracao da tabela base
DECLARE @COMANDO_CRIACAO_TABELA VARCHAR(200) = 'DECLARE ' + @NOMETABELA + ' TABLE (ID INT, NOME VARCHAR(50))'
DECLARE @COMANDO_CRIACAO_TABELA_AJUSTADO VARCHAR(200)

-- Cria o comando para criaçãod das tabelas
WHILE @CONTADOR < @QTDCOLUNAS
BEGIN
	
	SET @COMANDO_CRIACAO_TABELA_AJUSTADO = REPLACE(@COMANDO_CRIACAO_TABELA, '_', @CONTADOR)

	SET @COMANDO = @COMANDO + @COMANDO_CRIACAO_TABELA_AJUSTADO + CHAR(13)

	SET @CONTADOR = @CONTADOR + 1
	
END

-- Reseta contador global
SET @CONTADOR = 0

-- Adicionado variável para uso global do comando
SET @COMANDO = @COMANDO + 'DECLARE @IDADICIONADO INT' + CHAR(13)

-- Percorre todos os registros quebrando os dados por tabela
WHILE @CONTADOR < @QTDTOTALREGISTROS
BEGIN
	
	DECLARE @CONTADOR_TABELAS INT = 0

	WHILE @CONTADOR_TABELAS < @QTDCOLUNAS
	BEGIN
		
		SET @COMANDO = @COMANDO + 
		'SELECT TOP 1 @IDADICIONADO = ID FROM @TODOSITENS' + CHAR(13) +
		REPLACE('INSERT INTO ' + @NOMETABELA + ' (ID, NOME) SELECT TOP 1 ID, NOME FROM @TODOSITENS WHERE ID = @IDADICIONADO ', '_', @CONTADOR_TABELAS) + CHAR(13) +
		'DELETE FROM @TODOSITENS WHERE ID = @IDADICIONADO '
		
		SET @CONTADOR_TABELAS = @CONTADOR_TABELAS + 1
		SET @CONTADOR = @CONTADOR + 1

	END

END

-- Reseta contador global
SET @CONTADOR = 0

-- Comando para declaracao da tabela base
DECLARE @COMANDO_SELECT_TABELA VARCHAR(200) = 'SELECT* FROM ' + @NOMETABELA
DECLARE @COMANDO_SELECT_TABELA_AJUSTADO VARCHAR(200)

-- Cria o comando select dos dados
WHILE @CONTADOR < @QTDCOLUNAS
BEGIN
	
	SET @COMANDO_SELECT_TABELA_AJUSTADO = REPLACE(@COMANDO_SELECT_TABELA, '_', @CONTADOR)

	SET @COMANDO = @COMANDO + @COMANDO_SELECT_TABELA_AJUSTADO + CHAR(13)

	SET @CONTADOR = @CONTADOR + 1
	
END

SELECT @COMANDO AS ComandoGerado

EXECUTE (@COMANDO)
